### ISSUE TITLE
Use Case + UML

### ISSUE THREAD

**Issue by trevol1** [invisiblesushi/ITF20317-SE2018-G1#108]
Endre og lage flere use cases. Lage UML diagram til hvert bruksmønster.

- [x] -	Levering (langtid)
- [x] -	Parkering (langtid)
- [x] -	Parkering (korttid)
- [x] -	Lading av elbil (evt sammen i parkering)
- [x] -	Henting av bil
- [x] -	Sykkel
- [x] -	Klient
- [x] -	Reservasjon

**Comment by Benjamin113** [comment]
Closing because finished.
