### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by trevol1** [invisiblesushi/ITF20317-SE2018-G1#39]
| Valg av tittel |
|:----------|
## User Stories
Gå Inn På denne siden så får du mer informasjon om Hva en User story er: https://en.wikipedia.org/wiki/User_story

### Oppgaver for denne Tasken
- [x] Brainstorming om User stories. Mer om denne oppgaven finner du her: #36 
- [x] Gjør ferdig User storyen. Mer om denne oppgaven finner du her: #38 
- [ ] Oppdaterte user stories finnes her: 

### Beskrivelse
User stories, oppgaven består av å skrive om ulike utsagn som kan oppstå ved en gitt situasjon.

### Løsningsforslag
- [ ] Som en bruker, kan jeg bruke smart parkeringssystemet, for å spare tid.
- [ ] Som en passasjer, kan jeg bruke kollektivtransport, for å slippe og finne parkeringsplass i sentrum.
- [ ] Som en bruker, kan jeg betale med bankkort/Vipps, for å slippe mynt betaling.
- [ ] Som en syklist, kan jeg leie sykkel for å være mer miljøvennlig
- [ ] Som en elbil bruker, kan jeg lade bilen, for å få en fulladet bil.
- [ ] Som konsulent vil jeg parkere bilen min i langtidsparkeringen for å reise i jobbsammenheng.
- [ ] Som forelder vil jeg parkere bilen på korttidsparkering for å levere barna i barnehage/skole.
- [ ] Som ansatt vil jeg parkere på Grålum når jeg skal på jobb.
- [ ] Som kunde vil jeg parkere på korttidsparkering når jeg skal handle i matbutikk.
- [ ] Som besøkende kan jeg parkere på Grålum for å besøke Inspiria.
- [ ] Som hotellkunde, kan jeg parkere på Grålum for å bo på Quality Hotel.

**Comment by Benjamin113** [comment]
Closing.
