### ISSUE TITLE
Wireframes 

### ISSUE THREAD

**Issue by magfla** [invisiblesushi/ITF20317-SE2018-G1#43]
- [x] Create wireframes for the prototype

**Comment by vladjk** [comment]
Booking system wireframe
![booking system](https://user-images.githubusercontent.com/33227105/36205853-7e814afc-1190-11e8-9805-0618d01fc597.png)

**Comment by vladjk** [comment]
Terminal for parking
![terminal](https://user-images.githubusercontent.com/33227105/36206495-dc253d7e-1192-11e8-8971-0ff476283559.png)

**Comment by vladjk** [comment]
Can @magfla @invisiblesushi  @trevol1  @Benjamin113  give feedback of the wireframes.

**Comment by trevol1** [comment]
Understood! :)

**Comment by trevol1** [comment]
Very Good Wireframes! 👍
