### ISSUE TITLE
Powerpoint presentation about prototype

### ISSUE THREAD

**Issue by trevol1** [invisiblesushi/ITF20317-SE2018-G1#50]
Her er presentasjonen om prototypen:
[PrototypeSE.pptx](https://github.com/invisiblesushi/ITF20317-SE2018-G1/files/1728028/PrototypeSE.pptx)

**Comment by trevol1** [comment]
Her er presentasjonen om prototypen:
[PrototypeSE.pptx](https://github.com/invisiblesushi/ITF20317-SE2018-G1/files/1728028/PrototypeSE.pptx)

**Comment by Swoy** [comment]
Heisann,

Husk å formidle til gruppa at når dere stenger en issue, så kan det være lurt å skrive hvorfor dere stenger den. Noen eksempler:
- closed as fixed
- closed as invalid
- closed because [insert reason here]
