### ISSUE TITLE
Close issue with explaining texts

### ISSUE THREAD

**Issue by Benjamin113** [invisiblesushi/ITF20317-SE2018-G1#52]
Hvordan closer man en issue med beskrivende tekst som Ole forklarte her: 
![image](https://user-images.githubusercontent.com/22592765/36351668-b100d20c-14ad-11e8-8cdf-4219448093ff.png)

**Comment by vladjk** [comment]
Du skriver en kommentar og trykker close issue.

**Comment by Benjamin113** [comment]
Closed as fixed.
