### ISSUE TITLE
Authorization - Diagram 

### ISSUE THREAD

**Issue by Benjamin113** [invisiblesushi/ITF20317-SE2018-G1#53]
Make a sequence diagram of the authorization. (terminal/app/web authorization) (?)
- [ ] Bil/bruker validering. Mer om denne oppgaven finner du her:
- [x] Validering av eksisterende bruker. Mer om denne oppgaven finner du her:
- [ ] Ny bruker. Mer om denne oppgaven finner du her:
- [x] Innlogging. Mer om denne oppgaven finner du her: #57 #58 #59

**Comment by invisiblesushi** [comment]
Kan gruppen legge diagrammene inn på hoveddokumentet?

**Comment by Benjamin113** [comment]
Closing because finished.
