### ISSUE TITLE
Brainstorming - Sequence diagram

### ISSUE THREAD

**Issue by trevol1** [invisiblesushi/ITF20317-SE2018-G1#56]
Brainstorming om sekvens diagram:

- Innlogging (bruker innlogging) 
   - App 
   - Webside
   - Terminal 
- Validering (validering av _userinput_)
   - Ny bruker (validering av ny bruker; finnes brukernavn fra før etc. ) 
   - Bruker validering (validering av eksisterende bruker) 
   - Bil/bruker validering (validere at en gitt bil hører til en gitt bruker) 
- Parkering 
   - Bil parkering (bruker leverer bil --> robot parkerer bil) 
   - Hente bil (bruker vil hente bil  --> robot henter og leverer)
- _SystemServices_ (tenkes å utføres av sentralserver) 
    - Finne egnet robot for å parkere / hente bil (køsystem av noe slag?) 
    - Gjøre tidsberegninger og oppdater databasen (for statistiske formål)

**Comment by magfla** [comment]
Closing this because we got some ideas to work on.
