### ISSUE TITLE
Class diagram - Defining relevant classes

### ISSUE THREAD

**Issue by magfla** [invisiblesushi/ITF20317-SE2018-G1#62]
# Whats this?
An overview over the classes that needs modeling.

## General classes:
- _Vehicle_ (with at least two subclasses) 
    - _Electric_
    - _Fossile_
    - _Other_
    - _Motorcycle_
- _Person_ (superclass)
    - _User_
    - _Employee_
     - _Admin_
      - _Maintenance_
## Parking related classes
- _ParkingOverview_ (contains a datastructure containing the different _ParkingSections_, and _more_)
- _ParkingSection_ (contains a _Map_ of sorts over _Parkings_ in a given section. Also _Location_ of the _ParkingSection_)
- _Parking_ (a single parking (Google translated 'parkeringsplass' to simply 'parking'). Contains _Location_ of the _Parking_ and members for determining weather the _Parking_ is occupied, which _Car_ is there amongst others) 
- _Location_ (structure for identifying a specific parking location (i.e which row / column)) 

## Datastructures 
- _Stack_`<T>` (LIFO principle) 
- _Queue_`<T>` (FIFO principle) 
- _Hashtable_`<T,T>` (for mapping _Parking_ and _Car_)

**Comment by trevol1** [comment]
Task completed, close issue.
