### ISSUE TITLE
Prototype (redo)

### ISSUE THREAD

**Issue by Benjamin113** [invisiblesushi/ITF20317-SE2018-G1#69]
Lage en ny prototype som Terje vil ha den.

Terje ville ha en prototype av "user interface", for de som skal booke p-plasser. 
(Mer som denne)
![image](https://user-images.githubusercontent.com/22592765/36537986-1c7898ea-17d2-11e8-9d40-bafe63175bda.png)

Vlad og meg (Benjamin) kan snakke om dette og gjøre det sammen til hovedrapporten.

**Comment by vladjk** [comment]
Roger that

**Comment by Benjamin113** [comment]
Prototype for booking til arrangement (front-end)

Innloggingsside
Booke antall plasser 
Få reservasjonsnummer for forskjellige «soner»

**Comment by invisiblesushi** [comment]
Hva skal prototypen som skal brukes i hovedrapporten være om?
Mobil app?
Web klient?
Booking?

**Comment by Benjamin113** [comment]
front end til booking for arrangement. Den oppgaven vi presenterte for Terje, men som vi gjorde helt feil. Hvis vi ikke trenger den i hovedrapporten er det bare å droppe den, men tenkte siden det var en "innlevering" så kunne vi ta den med.

**Comment by invisiblesushi** [comment]
Foreløpig prototype eksempel

![image](https://user-images.githubusercontent.com/6609276/38061554-f5a608a4-32ef-11e8-8159-39dd230d3713.png)

**Comment by magfla** [comment]
Bra, bare gjør om Coop Extra Grålum  og andre tilsvarende. Ha språket på norsk på første bildet (innlogging), slik at det er konsistent. Bytte kl format?

**Comment by magfla** [comment]
Og andre stavefeil😊
