### ISSUE TITLE
Feedback on Proposed solutions, sequence diagrams & class diagrams

### ISSUE THREAD

**Issue by Swoy** [invisiblesushi/ITF20317-SE2018-G1#79]
Here is some feedback on your latest release; `Proposed solutions, sequence diagrams & class diagrams`.

### References
When you write the proposal, references are imperative. What made you make the choices you did? It's not enough to just say that you propose a solution based on a hunch. You need to put weight on the proposal by referencing research, surveys, interviews and other factors that lead you to decide what you did.

### Diagrams
Your diagrams look decent, you should format the descriptions better, the readability suffers greatly. Please format this properly and put descriptions below the diagrams. It's better to see each diagram first and then read about them after.

**Comment by invisiblesushi** [comment]
Feedback discussed in group workshop
