### ISSUE TITLE
What to do this week (5-11.03.18):

### ISSUE THREAD

**Issue by Benjamin113** [invisiblesushi/ITF20317-SE2018-G1#86]
- Tilstandsmaskiner (Magne, Trevo)
- Kravspekk (Daniel, Magne, ?)
- Finne spørsmål til stud. ass. - til neste uke.
- Skrive om/ fullføre domenebeskrivelse (Benjamin)
- Planlegge neste uke

**Comment by magfla** [comment]
Tror dette er overflødig, det holder å lage issues og koble dem opp mot "projects". Tror jeg.
