### ISSUE TITLE
State machines

### ISSUE THREAD

**Issue by Benjamin113** [invisiblesushi/ITF20317-SE2018-G1#90]
| State machines |
|:----------|
|_Vi skal levere tilstandsmaskiner basert på tidligere leveranser_; |

## Tilstandsmaskiner

| Notat|
|:----------|
| Dette er en "umbrella issue" for tilstandsmaskiner   |
Informasjon om tilstandsmaskiner : (les her: #89) 

### Oppgaver for denne tasken
- [x] Brainstorming. Mer om denne oppgaven finner du her: #80 
- [x] Lage tilstandsdiagrammer
- [x] Levere tilstandsdiagrammer

### Beskrivelse
Her skal dere levere tilstandsmaskiner.

_Dere skal levere 1-2 tilstandsmaskiner basert på tidligere leveranser._

### Løsningsforslag
_Her skriver dere (over tid) det som blir fremarbeidet gjennom oppgaven som er beskrevet, på en slik måte at det kan benyttes til en eventuell rapport. Om dette er en oppgave som ikke skal inn i rapporten, så skal det skrives en rapport her om hvordan det ble løst og hva som ble gjort, samt resultatet av det som ble gjort._

### Ekstra informasjon

**Comment by invisiblesushi** [comment]
Info link: https://www.uml-diagrams.org/state-machine-diagrams.html

**Comment by magfla** [comment]
Finished, closing issue.
