### ISSUE TITLE
Requirement specification

### ISSUE THREAD

**Issue by Benjamin113** [invisiblesushi/ITF20317-SE2018-G1#91]
## Kravspesifikasjon

| Notat|
|:----------|
| Dette er en "umbrella issue" for kravspesifikasjon   |

### Oppgaver for denne tasken
- [x] Generell kravspekk for Grålum 
- [x] Langtidsparkeringsystem (husk elbil)
- [x] Korttidsparkeringsystem (husk elbil) 
- [x] Sykkelsystem
- [x] Kolletkivtransport
- [x] Klient ( hjemmeside & app)
- [x] Server

- [x] Database

### Beskrivelse
Skrive ferdig nytt kravspekk. Skriv detaljert og presist.

### Ekstra informasjon

**Comment by invisiblesushi** [comment]
Skriver om hele kravspesifikasjonen i riktig format på hoveddokumentet.

**Comment by invisiblesushi** [comment]
Ferdig, ligger på hoveddokument
