### ISSUE TITLE
Electric car - parking

### ISSUE THREAD

**Issue by Benjamin113** [invisiblesushi/ITF20317-SE2018-G1#94]
Induksjonslading i bakken
automatisert tentakkel lading på langtidsparkeringen
plugglading på korttidsparkeringen
(korttid) skilt som viser om det er induksjon- eller plugg lading.

**Comment by invisiblesushi** [comment]
https://insideevs.com/tesla-shows-off-robotic-charger-prototype-that-finds-its-own-way-to-model-s-charge-port-video/

**Comment by Benjamin113** [comment]
Closing because finished.
