### ISSUE TITLE
Collective transport

### ISSUE THREAD

**Issue by Benjamin113** [invisiblesushi/ITF20317-SE2018-G1#96]
Selvkjørende buss.
"beepe" bankortet på automat for å betale billett.
Maksgrense på ??? per mnd. for bussbilletter.
Rullbom for å komme på bussen.
Østfold kollektiv vil være et eksternt system på Grålum.

**Comment by invisiblesushi** [comment]
Bør være en månedlig max grense på beløp,
Bør bruke bankkort siden alle har det. eller annen NFC teknologi

**Comment by Benjamin113** [comment]
closing because finished
